"""
Feedback Agent Service - LangChain ReAct 기반 평가 에이전트
===========================================================

LangChain의 ReAct (Reasoning + Acting) 패턴을 사용하여 사용자 응답을 평가합니다.

동작 방식:
1. Thought: "발음을 평가해야 한다"
2. Action: pronunciation_analyzer 실행
3. Observation: 발음 점수 75점
4. Thought: "문법도 확인해야 한다"
5. Action: grammar_checker 실행
... (반복)
Final Answer: {"needs_correction": true, "scores": {...}}

Author: Generated by Claude Code
Created: 2025-01-01
"""

import asyncio
import logging
import json
from typing import Dict, List, Optional

from langchain.agents import initialize_agent, AgentType, Tool
from langchain_community.llms import Ollama
from langchain_openai import ChatOpenAI
from langchain.schema import SystemMessage

from app.config import settings
from app.roleplaying.services.azure_speech_service import azure_speech_service

logger = logging.getLogger(__name__)


class FeedbackAgentService:
    """LangChain 기반 피드백 평가 에이전트 (ReAct 패턴)"""

    def __init__(self):
        """초기화"""
        self.llm = self._get_llm()
        self.agent = self._create_agent()
        logger.info(f"FeedbackAgentService initialized with {settings.FEEDBACK_LLM_PROVIDER}")

    def _get_llm(self):
        """환경변수에 따라 LLM 선택"""
        if settings.FEEDBACK_LLM_PROVIDER == "openai":
            logger.info("Using OpenAI LLM for feedback")
            return ChatOpenAI(
                model=settings.OPENAI_MODEL,
                api_key=settings.openai_api_key,
                temperature=0.3
            )
        else:  # Default: Ollama
            logger.info("Using Ollama LLM for feedback")
            return Ollama(
                model=settings.OLLAMA_MODEL,
                base_url=settings.OLLAMA_BASE_URL
            )

    def _create_agent(self):
        """ReAct Agent 생성"""
        tools = [
            Tool(
                name="pronunciation_analyzer",
                func=self._analyze_pronunciation,
                description="분석 Audio의 발음 품질을 Azure Speech API로 평가합니다. Input: audio_bytes와 reference_text. Output: pronunciation_score (0-100)."
            ),
            Tool(
                name="grammar_checker",
                func=self._check_grammar,
                description="사용자의 응답에서 문법 오류를 확인합니다. Input: user_text. Output: has_error (bool)와 error_description."
            ),
            Tool(
                name="context_evaluator",
                func=self._evaluate_context,
                description="사용자의 응답이 대화 맥락에 적절한지 평가합니다. Input: user_text와 conversation_summary. Output: relevance_score (0-100)."
            )
        ]

        # ReAct Agent 생성
        agent = initialize_agent(
            tools,
            self.llm,
            agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
            verbose=True,
            max_iterations=5,
            early_stopping_method="generate"
        )

        return agent

    async def evaluate_response_fast(
        self,
        user_text: str,
        audio_data: Optional[bytes],
        conversation_history: list,
        scenario_context: dict,
        retry_count: int
    ) -> Dict:
        """
        빠른 응답 평가 (점수만 먼저 전송)

        Args:
            user_text: 사용자 STT 결과 텍스트
            audio_data: 사용자 오디오 데이터 (발음 평가용)
            conversation_history: 대화 히스토리
            scenario_context: 시나리오 컨텍스트 (my_role, ai_role, current_question)
            retry_count: 현재 질문 재시도 횟수

        Returns:
            {
                "needs_correction": bool,
                "primary_issue": str (pronunciation/grammar/relevance),
                "scores": {
                    "pronunciation_score": int,
                    "grammar_score": int,
                    "relevance_score": int,
                    "overall_score": int
                },
                "feedback_text": str,
                "retry_count": int
            }
        """
        try:
            # 병렬 평가 (점수만 먼저)
            pronunciation, grammar, relevance = await asyncio.gather(
                self._evaluate_pronunciation_async(audio_data, user_text),
                self._evaluate_grammar_async(user_text),
                self._evaluate_relevance_async(user_text, conversation_history, scenario_context)
            )

            # 평가 점수 정규화 (0-100)
            pronunciation_score = max(0, min(100, pronunciation.get("score", 70)))
            grammar_score = max(0, min(100, grammar.get("score", 70)))
            relevance_score = max(0, min(100, relevance.get("score", 70)))

            # 종합 점수 (평균)
            overall_score = int((pronunciation_score + grammar_score + relevance_score) / 3)

            # 교정 필요 여부 판단
            needs_correction, primary_issue = self._judge_correction_needed(
                pronunciation_score,
                grammar_score,
                relevance_score,
                retry_count
            )

            # 피드백 텍스트 생성 (백그라운드에서도 실행)
            feedback_text = await self._generate_feedback_text_async(
                user_text,
                pronunciation,
                grammar,
                relevance,
                needs_correction
            )

            return {
                "needs_correction": needs_correction,
                "primary_issue": primary_issue,
                "scores": {
                    "pronunciation_score": int(pronunciation_score),
                    "grammar_score": int(grammar_score),
                    "relevance_score": int(relevance_score),
                    "overall_score": overall_score
                },
                "feedback_text": feedback_text,
                "retry_count": retry_count
            }

        except Exception as e:
            logger.error(f"Response evaluation failed: {e}", exc_info=True)
            # Fallback: 교정 없이 진행
            return {
                "needs_correction": False,
                "primary_issue": "error",
                "scores": {
                    "pronunciation_score": 70,
                    "grammar_score": 70,
                    "relevance_score": 70,
                    "overall_score": 70
                },
                "feedback_text": "평가 중 오류가 발생했습니다. 다음 질문으로 진행합니다.",
                "retry_count": retry_count
            }

    def _analyze_pronunciation(self, audio_data: Optional[bytes], reference_text: str) -> str:
        """발음 분석 (Tool)"""
        if not audio_data:
            return json.dumps({"score": 70, "feedback": "음성 분석 불가"})

        # Azure Speech 호출 (동기 래퍼)
        result = asyncio.run(
            azure_speech_service.assess_pronunciation(audio_data, reference_text)
        )

        if result.get("success"):
            return json.dumps({
                "score": result.get("pronunciation_score", 70),
                "feedback": f"발음 점수: {result.get('pronunciation_score', 70)}점"
            })
        else:
            return json.dumps({"score": 70, "feedback": "발음 분석 실패"})

    def _check_grammar(self, user_text: str) -> str:
        """문법 검사 (Tool)"""
        # LLM으로 문법 검사
        prompt = f"""다음 영문 문장의 문법을 확인하세요:
"{user_text}"

응답 형식:
- has_error: true/false
- error_description: 오류 설명 (오류가 없으면 "문법이 정확합니다")
- score: 문법 점수 (0-100)

JSON 형식으로 응답하세요:
{{"has_error": bool, "error_description": str, "score": int}}"""

        try:
            response = self.llm.invoke(prompt)
            # JSON 파싱 시도
            result = json.loads(response.content)
            score = result.get("score", 70 if result.get("has_error") else 90)
            return json.dumps({"score": score, "feedback": result.get("error_description", "")})
        except Exception as e:
            logger.error(f"Grammar check failed: {e}")
            return json.dumps({"score": 75, "feedback": "문법 검사 불가"})

    def _evaluate_context(self, user_text: str, conversation_summary: str) -> str:
        """맥락 평가 (Tool)"""
        # LLM으로 맥락 평가
        prompt = f"""대화 맥락에서 사용자의 응답이 얼마나 적절한지 평가하세요:

현재 대화 맥락:
{conversation_summary}

사용자 응답:
"{user_text}"

평가 기준:
- 질문에 직접 답변했는가?
- 관련성이 있는가?
- 충분한 길이인가?

JSON 형식으로 응답하세요:
{{"score": int(0-100), "feedback": "평가 의견"}}"""

        try:
            response = self.llm.invoke(prompt)
            result = json.loads(response.content)
            score = result.get("score", 70)
            return json.dumps({"score": score, "feedback": result.get("feedback", "")})
        except Exception as e:
            logger.error(f"Context evaluation failed: {e}")
            return json.dumps({"score": 75, "feedback": "맥락 평가 불가"})

    async def _evaluate_pronunciation_async(
        self,
        audio_data: Optional[bytes],
        reference_text: str
    ) -> Dict:
        """비동기 발음 평가"""
        if not audio_data:
            return {"score": 70, "feedback": "음성 데이터 없음"}

        try:
            result = await azure_speech_service.assess_pronunciation(audio_data, reference_text)
            if result.get("success"):
                return {
                    "score": result.get("pronunciation_score", 70),
                    "feedback": f"발음: {result.get('pronunciation_score', 70)}점"
                }
            return {"score": 70, "feedback": result.get("error_message", "발음 분석 실패")}
        except Exception as e:
            logger.error(f"Pronunciation evaluation failed: {e}")
            return {"score": 70, "feedback": str(e)}

    async def _evaluate_grammar_async(self, user_text: str) -> Dict:
        """비동기 문법 평가"""
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(None, self._check_grammar_json, user_text)

    async def _evaluate_relevance_async(
        self,
        user_text: str,
        conversation_history: list,
        scenario_context: dict
    ) -> Dict:
        """비동기 맥락 평가"""
        # 대화 컨텍스트 생성
        context = self._build_conversation_context(conversation_history, scenario_context)

        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            None,
            self._evaluate_context_json,
            user_text,
            context
        )

    def _check_grammar_json(self, user_text: str) -> Dict:
        """문법 검사 (JSON 결과)"""
        try:
            result_str = self._check_grammar(user_text)
            return json.loads(result_str)
        except:
            return {"score": 75, "feedback": ""}

    def _evaluate_context_json(self, user_text: str, context: str) -> Dict:
        """맥락 평가 (JSON 결과)"""
        try:
            result_str = self._evaluate_context(user_text, context)
            return json.loads(result_str)
        except:
            return {"score": 75, "feedback": ""}

    def _judge_correction_needed(
        self,
        pronunciation_score: float,
        grammar_score: float,
        relevance_score: float,
        retry_count: int
    ) -> tuple:
        """
        교정 필요 여부 판단

        Returns:
            (needs_correction: bool, primary_issue: str)
        """
        # 재시도 초과 시 강제 통과
        if retry_count >= settings.FEEDBACK_MAX_RETRY_PER_QUESTION:
            return False, "max_retries_exceeded"

        # 기준값
        pron_threshold = settings.FEEDBACK_PRONUNCIATION_THRESHOLD
        gram_threshold = settings.FEEDBACK_GRAMMAR_THRESHOLD
        relev_threshold = settings.FEEDBACK_RELEVANCE_THRESHOLD

        # 교정 필요 조건 판단
        primary_issue = None

        if pronunciation_score < pron_threshold:
            primary_issue = "pronunciation"
        elif grammar_score < gram_threshold:
            primary_issue = "grammar"
        elif relevance_score < relev_threshold:
            primary_issue = "relevance"

        needs_correction = primary_issue is not None
        return needs_correction, primary_issue or "none"

    async def _generate_feedback_text_async(
        self,
        user_text: str,
        pronunciation: Dict,
        grammar: Dict,
        relevance: Dict,
        needs_correction: bool
    ) -> str:
        """피드백 텍스트 생성 (비동기)"""
        loop = asyncio.get_event_loop()
        return await loop.run_in_executor(
            None,
            self._generate_feedback_text_sync,
            user_text,
            pronunciation,
            grammar,
            relevance,
            needs_correction
        )

    def _generate_feedback_text_sync(
        self,
        user_text: str,
        pronunciation: Dict,
        grammar: Dict,
        relevance: Dict,
        needs_correction: bool
    ) -> str:
        """피드백 텍스트 생성 (동기)"""
        try:
            feedback_parts = []

            # 발음 피드백
            if pronunciation.get("feedback"):
                feedback_parts.append(f"발음: {pronunciation['feedback']}")

            # 문법 피드백
            if grammar.get("feedback"):
                feedback_parts.append(f"문법: {grammar['feedback']}")

            # 맥락 피드백
            if relevance.get("feedback"):
                feedback_parts.append(f"맥락: {relevance['feedback']}")

            # 최종 메시지
            if needs_correction:
                feedback_text = " | ".join(feedback_parts)
                feedback_text += "\n다시 한 번 시도해주세요."
            else:
                feedback_text = "좋습니다! 계속 진행하겠습니다."

            return feedback_text

        except Exception as e:
            logger.error(f"Feedback generation failed: {e}")
            return "평가를 완료했습니다."

    def _build_conversation_context(self, history: list, scenario: dict) -> str:
        """대화 컨텍스트 구성"""
        context_parts = []

        # 시나리오 정보
        if scenario:
            context_parts.append(f"역할: {scenario.get('my_role', '')} vs {scenario.get('ai_role', '')}")
            context_parts.append(f"현재 질문: {scenario.get('current_question', '')}")

        # 최근 대화 히스토리 (최대 3턴)
        if history:
            context_parts.append("\n최근 대화:")
            for turn in history[-6:]:  # 최근 3턴 (사용자 + AI 쌍)
                speaker = turn.get("speaker", "")
                text = turn.get("text", "")[:100]
                context_parts.append(f"{speaker}: {text}")

        return "\n".join(context_parts)


# 전역 인스턴스
feedback_agent_service = FeedbackAgentService()
