"""
Feedback Agent Service (Legacy Compatibility Layer)
=====================================================
⚠️ DEPRECATED: 하위 호환성을 위해 유지됩니다.

마이그레이션 가이드:
    기존: from app.roleplaying.services.feedback_agent_service import feedback_agent_service
    신규: from app.roleplaying.services.dependencies import FeedbackOrchestratorDep
    신규: from app.roleplaying.services.feedback_service_refactored import FeedbackOrchestratorImpl

구조:
    - FeedbackAgentService: 레거시 호환성 Facade
    - 내부적으로 feedback_service_refactored의 구현체들을 위임
    - 모든 메서드는 Deprecated 경고 발생
    - 기능은 동일하게 유지

목표:
    - 기존 코드 파괴 방지
    - 점진적 마이그레이션 지원
    - 새 코드는 feedback_service_refactored 직접 사용

Author: Generated by Claude Code
Created: 2025-01-01
"""

import warnings
import logging
from typing import Dict, List, Optional, Any

from app.roleplaying.services.interfaces import FeedbackOrchestrator

logger = logging.getLogger(__name__)


class FeedbackAgentService:
    """⚠️ DEPRECATED: 응답 평가 서비스 (레거시)

    마이그레이션:
        FeedbackAgentService().evaluate_response_fast(...)
        → FeedbackOrchestratorImpl(...).evaluate_response_fast(...)
    """

    def __init__(self, feedback_orchestrator: FeedbackOrchestrator = None):
        """
        FeedbackAgentService 초기화

        Args:
            feedback_orchestrator: FeedbackOrchestrator 구현체 (의존성 주입)

        ⚠️ Deprecated: 새 코드는 feedback_service_refactored의 구현체 직접 사용
        """
        warnings.warn(
            "FeedbackAgentService is deprecated. Use specific service classes:\\n"
            "- FeedbackOrchestratorImpl for orchestrating all feedback evaluation\\n"
            "- GrammarEvaluatorImpl for grammar evaluation\\n"
            "- RelevanceEvaluatorImpl for relevance evaluation\\n"
            "- PronunciationEvaluator for pronunciation evaluation\\n"
            "Import from app.roleplaying.services.feedback_service_refactored",
            DeprecationWarning,
            stacklevel=2
        )

        # Lazy import to avoid circular dependency
        if feedback_orchestrator is None:
            from app.roleplaying.services.dependencies import get_feedback_orchestrator
            feedback_orchestrator = get_feedback_orchestrator()

        self._orchestrator = feedback_orchestrator
        logger.info("FeedbackAgentService initialized with injected orchestrator")

    async def evaluate_response_fast(
        self,
        user_text: str,
        audio_data: Optional[bytes],
        conversation_history: list,
        scenario_context: dict,
        retry_count: int
    ) -> Dict[str, Any]:
        """
        빠른 응답 평가 (위임)

        Args:
            user_text: 사용자 STT 결과 텍스트
            audio_data: 사용자 오디오 데이터
            conversation_history: 대화 히스토리
            scenario_context: 시나리오 컨텍스트
            retry_count: 현재 질문 재시도 횟수

        Returns:
            평가 결과 딕셔너리
        """
        return await self._orchestrator.evaluate_response_fast(
            user_text=user_text,
            audio_data=audio_data,
            conversation_history=conversation_history,
            scenario_context=scenario_context,
            retry_count=retry_count
        )


# ============================================
# 전역 인스턴스 (레거시 호환성용)
# ============================================

# ⚠️ DEPRECATED: 새 코드는 dependencies.py의 FeedbackOrchestratorDep를 사용하세요
def _create_legacy_feedback_agent():
    """레거시 피드백 에이전트 생성 (필요시에만 인스턴스화)"""
    return FeedbackAgentService()


# 지연 초기화: 처음 사용시에만 생성
_feedback_agent_service_instance = None


def get_feedback_agent_service_instance():
    """레거시 전역 인스턴스 반환"""
    global _feedback_agent_service_instance
    if _feedback_agent_service_instance is None:
        _feedback_agent_service_instance = _create_legacy_feedback_agent()
    return _feedback_agent_service_instance


# 직접 접근용 (하위호환성)
def __getattr__(name):
    """모듈 수준 속성 접근시 지연 초기화"""
    if name == "feedback_agent_service":
        instance = get_feedback_agent_service_instance()
        globals()["feedback_agent_service"] = instance  # 이후 접근 최적화
        return instance
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
