"""
Azure Speech Free Tier 사용량 추적기
=====================================

Redis를 사용하여 일일 사용량을 추적하고, Free Tier 제한을 관리합니다.

주요 기능:
- 일일 사용량 카운트
- 사용 가능 여부 확인
- 자동 일일 리셋
- 사용량 통계

Author: Generated by Claude Code
Created: 2025-01-01
"""

import logging
from datetime import datetime, timezone, timedelta
from typing import Optional

from redis import asyncio as aioredis

from app.config import settings

logger = logging.getLogger(__name__)


class AzureUsageTracker:
    """Azure Speech Free Tier 사용량 추적기"""

    def __init__(self):
        """초기화"""
        self.redis_url = settings.REDIS_URL
        self.daily_limit = settings.AZURE_SPEECH_DAILY_LIMIT
        self.redis_client: Optional[aioredis.Redis] = None
        self.initialized = False

    async def init(self) -> None:
        """Redis 연결 초기화"""
        try:
            self.redis_client = await aioredis.from_url(
                self.redis_url,
                encoding="utf8",
                decode_responses=True
            )
            # 연결 테스트
            await self.redis_client.ping()
            self.initialized = True
            logger.info("AzureUsageTracker initialized successfully")
        except Exception as e:
            logger.error(f"Failed to initialize AzureUsageTracker: {e}")
            self.initialized = False

    async def close(self) -> None:
        """Redis 연결 종료"""
        if self.redis_client:
            await self.redis_client.close()
            logger.info("AzureUsageTracker connection closed")

    def _get_today_key(self) -> str:
        """오늘의 Redis 키 생성 (UTC 기준)"""
        today = datetime.now(timezone.utc).date()
        return f"azure_speech:daily_usage:{today.isoformat()}"

    def _get_warning_key(self) -> str:
        """사용량 경고 키"""
        return f"azure_speech:warning_sent:{datetime.now(timezone.utc).date().isoformat()}"

    async def can_use_azure(self) -> bool:
        """
        Azure Speech API 사용 가능 여부 확인

        Returns:
            True if 사용 가능, False if 일일 제한 초과
        """
        if not self.initialized:
            logger.warning("AzureUsageTracker not initialized, allowing usage")
            return True

        try:
            key = self._get_today_key()
            current_usage = await self.redis_client.get(key)
            usage_count = int(current_usage) if current_usage else 0

            can_use = usage_count < self.daily_limit

            if can_use:
                logger.debug(f"Azure usage allowed. Current: {usage_count}/{self.daily_limit}")
            else:
                logger.warning(f"Azure usage limit exceeded. Current: {usage_count}/{self.daily_limit}")

            return can_use

        except Exception as e:
            logger.error(f"Failed to check usage limit: {e}")
            return True  # 오류 시 사용 허용

    async def increment_usage(self) -> int:
        """
        사용량 증가

        Returns:
            증가 후 사용량
        """
        if not self.initialized:
            return 0

        try:
            key = self._get_today_key()

            # 사용량 증가
            new_usage = await self.redis_client.incr(key)

            # TTL 설정 (자정까지 유지, 최대 24시간)
            if new_usage == 1:  # 첫 사용일 때만 TTL 설정
                # 다음 자정(UTC) 까지의 초 계산
                tomorrow = datetime.now(timezone.utc).date() + timedelta(days=1)
                tomorrow_midnight = datetime.combine(tomorrow, datetime.min.time()).replace(
                    tzinfo=timezone.utc
                )
                seconds_until_midnight = int((tomorrow_midnight - datetime.now(timezone.utc)).total_seconds())

                await self.redis_client.expire(key, max(seconds_until_midnight, 1))

            # 80% 사용 시 경고
            if new_usage == int(self.daily_limit * 0.8):
                await self._send_warning(new_usage)

            logger.info(f"Azure usage incremented. Current: {new_usage}/{self.daily_limit}")
            return new_usage

        except Exception as e:
            logger.error(f"Failed to increment usage: {e}")
            return 0

    async def get_today_usage(self) -> int:
        """오늘의 사용량 조회"""
        if not self.initialized:
            return 0

        try:
            key = self._get_today_key()
            usage = await self.redis_client.get(key)
            return int(usage) if usage else 0
        except Exception as e:
            logger.error(f"Failed to get usage: {e}")
            return 0

    async def get_remaining(self) -> int:
        """남은 사용량"""
        usage = await self.get_today_usage()
        return max(0, self.daily_limit - usage)

    async def get_usage_percentage(self) -> float:
        """사용량 퍼센티지 (0-100)"""
        usage = await self.get_today_usage()
        return (usage / self.daily_limit) * 100 if self.daily_limit > 0 else 0

    async def _send_warning(self, current_usage: int) -> None:
        """사용량 경고 발송"""
        try:
            warning_key = self._get_warning_key()

            # 이미 경고를 보냈으면 스킵
            already_warned = await self.redis_client.exists(warning_key)
            if already_warned:
                return

            # 경고 플래그 설정 (다음 날까지 유지)
            await self.redis_client.setex(
                warning_key,
                86400,  # 24시간
                "1"
            )

            percentage = (current_usage / self.daily_limit) * 100
            logger.warning(
                f"Azure Speech usage warning: {current_usage}/{self.daily_limit} ({percentage:.1f}%) reached"
            )
            # 실제로는 이메일 알림 등을 보낼 수 있음

        except Exception as e:
            logger.error(f"Failed to send warning: {e}")

    async def reset_today(self) -> None:
        """오늘의 사용량 리셋 (테스트용)"""
        if not self.initialized:
            return

        try:
            key = self._get_today_key()
            await self.redis_client.delete(key)
            logger.info(f"Azure usage reset for {key}")
        except Exception as e:
            logger.error(f"Failed to reset usage: {e}")


# 전역 인스턴스
usage_tracker = AzureUsageTracker()
