"""
Azure Speech Service - 발음 평가 서비스
=========================================

Azure Cognitive Services Speech API를 사용하여 사용자의 발음을 평가합니다.

주요 기능:
- 발음 점수 (0-100)
- 정확도, 유창성, 완성도 평가
- 단어별 상세 분석

Author: Generated by Claude Code
Created: 2025-01-01
"""

import asyncio
import json
import logging
from typing import Dict, Optional

from azure.cognitiveservices.speech import (
    SpeechConfig,
    SpeechRecognizer,
    PronunciationAssessmentConfig,
    PronunciationAssessmentGradingSystem,
    PronunciationAssessmentGranularity,
    ResultReason,
    PropertyId,
)
from azure.cognitiveservices.speech.audio import AudioConfig, PushAudioInputStream

from app.config import settings
from app.roleplaying.services.stt.audio_converter import AudioConverter

logger = logging.getLogger(__name__)


class AzureSpeechService:
    """Azure Speech 발음 평가 서비스"""

    def __init__(self):
        """Azure Speech Service 초기화"""
        self.converter = AudioConverter()
        if not settings.AZURE_SPEECH_KEY:
            logger.warning("AZURE_SPEECH_KEY not configured. Pronunciation assessment disabled.")
            self.enabled = False
            return

        self.enabled = True
        self.speech_config = SpeechConfig(
            subscription=settings.AZURE_SPEECH_KEY,
            region=settings.AZURE_SPEECH_REGION
        )
        logger.info(f"Azure Speech Service initialized. Region: {settings.AZURE_SPEECH_REGION}")

    async def assess_pronunciation(
        self,
        audio_data: bytes,
        reference_text: str,
        language: str = "en-US"
    ) -> Dict:
        """
        발음 평가 수행

        Args:
            audio_data: WAV 형식 오디오 바이너리 데이터
            reference_text: 참조 텍스트 (예: "Hello, how are you?")
            language: 언어 코드 (기본값: en-US)

        Returns:
            {
                "success": bool,
                "pronunciation_score": float,  # 0-100
                "accuracy_score": float,        # 0-100
                "fluency_score": float,         # 0-100
                "completeness_score": float,    # 0-100
                "words": [
                    {
                        "word": "hello",
                        "accuracy_score": 95,
                        "error_type": None
                    },
                    ...
                ],
                "error_message": str (실패 시)
            }
        """
        if not self.enabled:
            logger.warning("Azure Speech Service is disabled")
            return {
                "success": False,
                "error_message": "Azure Speech Service not configured"
            }

        try:
            # 비동기 스레드에서 동기 API 호출
            loop = asyncio.get_event_loop()
            result = await loop.run_in_executor(
                None,
                self._assess_pronunciation_sync,
                audio_data,
                reference_text,
                language
            )
            return result

        except Exception as e:
            logger.error(f"Pronunciation assessment failed: {e}", exc_info=True)
            return {
                "success": False,
                "error_message": str(e)
            }

    async def evaluate_pronunciation(
        self,
        audio_data: Optional[bytes],
        reference_text: str,
        language: str = "en-US"
    ) -> Dict:
        """
        Feedback 서비스 호환용 평가 메서드.

        audio_data가 없으면 발음 평가를 생략하고 기본 응답을 반환합니다.
        """
        if not audio_data:
            return {
                "success": False,
                "error_message": "No audio data provided",
                "pronunciation_score": 0
            }

        return await self.assess_pronunciation(
            audio_data=audio_data,
            reference_text=reference_text,
            language=language
        )

    def _assess_pronunciation_sync(
        self,
        audio_data: bytes,
        reference_text: str,
        language: str
    ) -> Dict:
        """
        동기 발음 평가 (executor에서 실행)

        Args:
            audio_data: WAV 형식 오디오 바이너리 데이터
            reference_text: 참조 텍스트
            language: 언어 코드

        Returns:
            평가 결과 딕셔너리
        """
        try:
            # Azure Speech SDK용 Push 오디오 스트림 생성
            audio_stream = PushAudioInputStream()

            # AudioConfig에 오디오 스트림 설정
            audio_config = AudioConfig(stream=audio_stream)

            # 음성 인식기 생성
            speech_recognizer = SpeechRecognizer(
                speech_config=self.speech_config,
                audio_config=audio_config,
                language=language
            )

            # Pronunciation Assessment 설정
            pronunciation_config = PronunciationAssessmentConfig(
                reference_text=reference_text,
                grading_system=PronunciationAssessmentGradingSystem.HundredMark,
                granularity=PronunciationAssessmentGranularity.Phoneme,
                enable_miscue=True
            )
            pronunciation_config.apply_to(speech_recognizer)

            # PCM → WAV 변환 (Azure 안정성 확보)
            wav_audio = self.converter.pcm_to_wav(audio_data)

            # 오디오 데이터를 스트림에 작성
            audio_stream.write(wav_audio)
            audio_stream.close()

            # 발음 평가 실행
            result = speech_recognizer.recognize_once()

            # 결과 상태 로깅
            logger.error(f"Recognition result reason: {result.reason}")
            logger.error(f"Recognition result text: {result.text if hasattr(result, 'text') else 'N/A'}")
            logger.error(f"Result properties keys: {list(result.properties.keys()) if hasattr(result, 'properties') else 'N/A'}")

            # 결과 분석
            if result.reason == ResultReason.RecognizedSpeech:
                return self._parse_pronunciation_result(result)

            elif result.reason == ResultReason.NoMatch:
                logger.warning(f"No speech recognized. NoMatch error: {result.no_match_details}")
                return {
                    "success": False,
                    "error_message": "No speech detected"
                }

            elif result.reason == ResultReason.Canceled:
                cancellation = result.cancellation_details
                logger.error(f"Speech Recognition canceled. Error: {cancellation.error_details}")
                return {
                    "success": False,
                    "error_message": f"Recognition canceled: {cancellation.error_details}"
                }

            else:
                return {
                    "success": False,
                    "error_message": "Unknown recognition result"
                }

        except Exception as e:
            logger.error(f"Pronunciation assessment sync failed: {e}", exc_info=True)
            return {
                "success": False,
                "error_message": str(e)
            }

    def _parse_pronunciation_result(self, result) -> Dict:
        """
        Azure Speech 결과 파싱

        Args:
            result: SpeechRecognitionResult 객체

        Returns:
            정규화된 결과 딕셔너리
        """
        try:
            # JSON 결과 파싱 (PropertyId enum 사용)
            json_result = result.properties.get(PropertyId.SpeechServiceResponse_JsonResult)

            if not json_result:
                available_props = list(result.properties.keys()) if hasattr(result, 'properties') else []
                result_text = result.text if hasattr(result, 'text') else 'N/A'
                logger.error(f"No JSON result in response. Result text: {result_text}")
                logger.error(f"Available properties: {available_props}")
                return {
                    "success": False,
                    "error_message": "No pronunciation assessment data in response",
                    "debug_info": {
                        "recognized_text": result_text,
                        "available_properties": available_props
                    }
                }

            pronunciation_result = json.loads(json_result)

            # 최상위 점수 추출
            nbest = pronunciation_result.get("NBest", [{}])[0]
            pronunciation_assessment = nbest.get("PronunciationAssessment", {})

            pronunciation_score = pronunciation_assessment.get("PronScore", 0)
            accuracy_score = pronunciation_assessment.get("AccuracyScore", 0)
            fluency_score = pronunciation_assessment.get("FluencyScore", 0)
            completeness_score = pronunciation_assessment.get("CompletenessScore", 0)

            # 단어별 상세 정보 추출
            words = []
            words_data = nbest.get("Words", [])
            for word_info in words_data:
                words.append({
                    "word": word_info.get("Word", ""),
                    "accuracy_score": word_info.get("PronunciationAssessment", {}).get("AccuracyScore", 0),
                    "error_type": word_info.get("PronunciationAssessment", {}).get("ErrorType", None)
                })

            logger.info(f"Pronunciation assessment completed. Score: {pronunciation_score}")

            return {
                "success": True,
                "recognized_text": result.text,
                "pronunciation_score": round(pronunciation_score, 2),
                "accuracy_score": round(accuracy_score, 2),
                "fluency_score": round(fluency_score, 2),
                "completeness_score": round(completeness_score, 2),
                "words": words
            }

        except Exception as e:
            logger.error(f"Failed to parse pronunciation result: {e}", exc_info=True)
            return {
                "success": False,
                "error_message": f"Result parsing failed: {str(e)}"
            }


# 전역 인스턴스
azure_speech_service = AzureSpeechService()
