#!/usr/bin/env python3
"""
Inspect actual httpx multipart body encoding to diagnose Spring2 integration issues.
"""

import asyncio
import httpx


async def test_multipart_body():
    """Inspect the actual multipart body generated by httpx"""

    print("=" * 80)
    print("Inspecting httpx multipart/form-data body encoding")
    print("=" * 80)

    # Create dummy data
    speaker = "user"
    text = "test utterance text"
    utterance_index = 0
    audio_data = b"AUDIO_DATA" * 10

    # Test: Using files parameter with (None, value) tuples for text fields
    print("\n[Current Implementation] Files parameter with (None, value) tuples")
    print("-" * 80)

    files = {
        "speaker": (None, speaker),
        "text": (None, text),
        "utterance_index": (None, str(utterance_index)),
        "audio": ("utterance_0.wav", audio_data, "audio/wav"),
    }

    async with httpx.AsyncClient() as client:
        # Build request and stream to get body
        req = client.build_request(
            "POST",
            "http://localhost:8081/internal/sessions/test-session-123/utterances",
            files=files,
        )

        print(f"Content-Type: {req.headers.get('content-type')}")
        print(f"\nRequest stream (_stream): {req.stream}")

        # For streaming requests, we need to access the content differently
        # Let's use sync client instead to see the full body
        pass

    # Use sync client to inspect body
    print("\n[Using httpx.Client for synchronous body inspection]")
    print("-" * 80)

    with httpx.Client() as client:
        req = client.build_request(
            "POST",
            "http://localhost:8081/internal/sessions/test-session-123/utterances",
            files=files,
        )

        print(f"Content-Type: {req.headers.get('content-type')}")
        print(f"\nRequest body (decoded where possible):")
        print("-" * 80)

        # Try to show the body as text (will have binary audio)
        try:
            body_str = req.content.decode('utf-8', errors='replace')
            # Show first 1500 chars to see structure
            print(body_str[:1500])
            print("\n...")
            print(f"\n[Body is {len(req.content)} bytes total]")
        except Exception as e:
            print(f"Error decoding body: {e}")
            print(f"Body length: {len(req.content)} bytes")
            print(req.content[:1500])

        # Now let's check if "text" field is actually in the body
        print("\n[Checking for form field names in body]")
        print("-" * 80)

        if b"text" in req.content:
            print("✓ Found 'text' field name in body")
            # Find the context around 'text'
            idx = req.content.find(b"text")
            print(f"  Context (50 bytes before and after):")
            start = max(0, idx - 50)
            end = min(len(req.content), idx + 100)
            context = req.content[start:end]
            print(f"  {context}")
        else:
            print("✗ 'text' field name NOT found in body")

        if b"speaker" in req.content:
            print("✓ Found 'speaker' field name in body")
        else:
            print("✗ 'speaker' field name NOT found in body")

        if b"utterance_index" in req.content:
            print("✓ Found 'utterance_index' field name in body")
        else:
            print("✗ 'utterance_index' field name NOT found in body")

        # Test alternative: using string values directly
        print("\n\n[Alternative: Files parameter with string tuples (filename, content)]")
        print("-" * 80)

        files_alt = {
            "speaker": (None, speaker),
            "text": (None, text),
            "utterance_index": (None, str(utterance_index)),
            "audio": ("utterance_0.wav", audio_data, "audio/wav"),
        }

        req_alt = client.build_request(
            "POST",
            "http://localhost:8081/internal/sessions/test-session-123/utterances",
            files=files_alt,
        )

        print(f"Content-Type: {req_alt.headers.get('content-type')}")

        if b"text" in req_alt.content:
            print("✓ Found 'text' field name in alternative body")
        else:
            print("✗ 'text' field name NOT found in alternative body")


if __name__ == "__main__":
    asyncio.run(test_multipart_body())